version: '3'

services:
# 月之暗面Kimi
  kimi-free-api:
    container_name: kimi-free-api
    image: vinlic/kimi-free-api:latest
    hostname: kimifree
    restart: always
    ports:
      - "10013:8000" #10013可以修改，8000不可以修改
    expose:
      - "8000"
    environment:
      - TZ=Asia/Shanghai

# 跃问StepChat
  step-free-api:
    container_name: step-free-api
    hostname: stepfree
    image: vinlic/step-free-api:latest
    restart: always
    ports:
      - "10014:8000"  #10019可以修改，8000不可以修改
    expose:
      - "8000"
    environment:
      - TZ=Asia/Shanghai

# 智谱清言GLM4
  glm-free-api:
    container_name: glm-free-api
    hostname: glmfree
    image: vinlic/glm-free-api:latest
    restart: always
    ports:
      - "10015:8000"  #10015可以修改，8000不可以修改
    expose:
      - "8000"
    environment:
      - TZ=Asia/Shanghai

# 通义千问Qwen-Max
  qwen-free-api:
    container_name: qwen-free-api
    hostname: qwenfree
    image: vinlic/qwen-free-api:latest
    restart: always
    ports:
      - "10016:8000"  #10016可以修改，8000不可以修改
    expose:
      - "8000"
    environment:
      - TZ=Asia/Shanghai

# 聆心智能Emohaa
  emohaa-free-api:
    container_name: emohaa-free-api
    hostname: emohaafree
    image: vinlic/emohaa-free-api:latest
    restart: always
    ports:
      - "10017:8000"  #10017可以修改，8000不可以修改
    expose:
      - "8000"
    environment:
      - TZ=Asia/Shanghai      

# 秘塔AI
  metaso-free-api:
    container_name: metaso-free-api
    hostname: metasofree
    image: vinlic/metaso-free-api:latest
    restart: always
    ports:
      - "10018:8000"  #10018可以修改，8000不可以修改
    expose:
      - "8000"
    environment:
      - TZ=Asia/Shanghai

# 讯飞星火SparkDesk
  spark-free-api:
    container_name: spark-free-api
    hostname: sparkfree
    image: vinlic/spark-free-api:latest
    restart: always
    ports:
      - "10019:8000"  #10019可以修改，8000不可以修改
    expose:
      - "8000"
    environment:
      - TZ=Asia/Shanghai
      
# api地址可以使用：http://hostname:prots
